### ISSUE TITLE
The page does not display quotation sheet content

### ISSUE THREAD

**Issue by utopianet** [vhpoet/xrpvalue.com#5]
When I deploy the application on tomcat, no error but the page does not display quotation sheet content , is there a solution？
![qq20140107221342](https://f.cloud.github.com/assets/6178793/1859586/03fead2a-77a6-11e3-8013-7eaa75f44d40.jpg)

**Comment by vhpoet** [comment]
@utopianet did you check the console? are there any exceptions?

**Comment by vhpoet** [comment]
@utopianet turns out the path needs to be the root for it to work. so http://localhost:8080
